home: /Users/faisal
name: faisalburhanudin
email: faisalburhanudin@gmail.com

dotfiles:
  - { name: .zshrc, dest: "{{ home }}" }
  - { name: starship.toml, dest: "{{ home }}/.config/" }
  - { name: .gitignore, dest: "{{ home }}" }
  - { name: .tmux.conf, dest: "{{ home }}" }
  - { name: .gitconfig, dest: "{{ home }}" }

