- name: "ensure homebrew tap tapped"
  shell: "brew tap {{ item }}"
  args:
    creates: "/opt/homebrew/Library/Taps/homebrew/{{ item | replace('/', '-') }}"
  loop:
    - "homebrew/cask-fonts"
    - "leoafarias/fvm"

- name: "ensure homebrew library installed"
  community.general.homebrew:
    name:
      - "black"
      - "fd"
      - "fzf"
      - "gcc"
      - "gnu-tar"
      - "go"
      - "groovy"
      - "htop"
      - "httpie"
      - "jq"
      - "kubernetes-cli"
      - "lazygit"
      - "navi"
      - "neovim"
      - "openjdk"
      - "redis"
      - "ripgrep"
      - "shfmt"
      - "starship"
      - "task"
      - "tmux"
      - "tree"
      - "wget"
      - "yq"
      - "zoxide"
      - "zsh-autosuggestions"
      - "gh"  # GitHub client
      - "jc"  # convert anything to json
      - "node"  # node.js
      - "yarn"  # node.js package manager
      - "watch"
      - "mysql-client"  # rogu need mysql client to get secret
      - "fvm"  #flutter manager
      - "yt-dlp"  # for download YouTube

    state: "present"

- name: "ensure homebrew cask installed"
  community.general.homebrew_cask:
    name:
      - "font-hack-nerd-font"
      - "spotify"
      - "google-cloud-sdk"
      - "visual-studio-code"
      - "notion"
      - "transmission"
      - "discord"
      - "figma"
      - "docker"
      - "todoist"
      - "slack"
      - "whatsapp"
      - "zoom"
      - "spectacle"  # easy window manager
      - "postman"
      - "another-redis-desktop-manager"
    state: "present"
