- name: "ensure homebrew tap tapped"
  shell: "brew tap {{ item }}"
  args:
    creates: "/opt/homebrew/Library/Taps/homebrew/{{ item | replace('/', '-') }}"
  loop:
    - "homebrew/cask-fonts"

- name: "ensure homebrew library installed"
  community.general.homebrew:
    name:
      - "black"
      - "fd"
      - "fzf"
      - "gcc"
      - "gnu-tar"
      - "go"
      - "groovy"
      - "htop"
      - "httpie"
      - "jq"
      - "kubernetes-cli"
      - "lazygit"
      - "navi"
      - "neovim"
      - "openjdk"
      - "redis"
      - "ripgrep"
      - "shfmt"
      - "starship"
      - "task"
      - "tmux"
      - "tree"
      - "wget"
      - "youtube-dl"
      - "yq"
      - "zoxide"
      - "zsh-autosuggestions"
      - "gh"  # GitHub client

    state: "present"

- name: "ensure homebrew cask installed"
  community.general.homebrew_cask:
    name:
      - "font-hack-nerd-font"
      - "spotify"
      - "google-cloud-sdk"
      - "visual-studio-code"
      - "notion"
      - "transmission"
      - "discord"
      - "figma"
      - "docker"
      - "todoist"
    state: "present"
